spring.application.name=gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

logging.level.root=INFO
logging.level.com.ayush.gateway=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO

# Route : Forward /api/** to devotee-service
spring.cloud.gateway.routes[0].id=devotee-service
spring.cloud.gateway.routes[0].uri=lb://DEVOTEE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/**


# Circuit Breaker (redirect to fallback endpoint if service fails)
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=devoteeCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback

# Circuit Breaker config
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.sliding-window-size=30
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.minimum-number-of-calls=20
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.failure-rate-threshold=80
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.devoteeCircuitBreaker.permitted-number-of-calls-in-half-open-state=3

logging.level.io.github.resilience4j.circuitbreaker=INFO
